# This script verifies the accuracy of kNN and naive Bayes predictions by the leave-one-out
# approach. The goal is to check whether the machine learning approaches add to the bare
# COVID-19 severity grade in terms of predicting 6-month lung lesions

# data and toolbox ----

  source('./tools/sys_tools.R')
  source('./tools/roc_toolbox.R')
  source('./tools/knn_tools.R')

  library(furrr)

  insert_head()
  
# data container ------
  
  cov_knn_verif <- list()
  
# script-specific functions ------
  
  cov_knn_verif$make_splits <- function(inp_tbl) {
    
    ## splits the given table into a list of test/train subsets
    ## generated by one-out principle
    
    one_in_vec <- rownames(inp_tbl)
    
    one_out_vec <- one_in_vec %>%
      map(function(x) rownames(inp_tbl)[rownames(inp_tbl) != x])
    
    splits <- map2(one_in_vec, 
                   one_out_vec, 
                   function(x, y) list(test = inp_tbl[x, ], 
                                       train = inp_tbl[y, ])) %>% 
      set_names(one_in_vec)
    
    
    return(splits)
    
  }
  
  cov_knn_verif$check_accuracy <- function(train, test_vec, outcome, test_fun = knn, ...) {
    
    ## compares the prediction with the real outcome
    
    if(nrow(test_vec) > 1) {
      
      stop('Function works only for single observaitons')
      
    }

    pred_outcome <- test_fun(train = train, 
                             test_vec = test_vec, 
                             outcome = outcome, ...)
    
    res_tbl <- tibble(pred_outcome = pred_outcome[[1]][1], 
                      true_outcome = test_vec[[outcome]][1])
    
    return(res_tbl)
    
  }
  
  cov_knn_verif$test_accuracy <- function(boot_split_lst, outcome, test_fun = knn, ...) {
    
    ## compares the prediction with the real outcome
    
    ## prediction
    
    pred_res <- boot_split_lst %>% 
      map_dfr(function(x) cov_knn_verif$check_accuracy(train = x$train, 
                                                       test_vec = x$test, 
                                                       outcome = outcome, 
                                                       test_fun = test_fun, ...)) %>% 
      mutate(ID = names(boot_split_lst))
    
    return(pred_res)
    
  }
  
  cov_knn_verif$calculate_stats <- function(pred_results) {
    
    ## claculates prediction stats (Se, sp, accuracy)
    ## for the whole cohort and the severity subsets (mild - internediate vs severe-critical)
    
    ## IDs associated with the severity groups
    
    sev_ids <- cov_data$long_data %>%
      filter(time == 0) %>% 
      dlply(.(pat_group), function(x) x$ID) %>% 
      c(list(cohort = pred_results$ID))
    
    group_ids <- list(cohort = pred_results$ID, 
                      mild = c(sev_ids$G1, sev_ids$G2), 
                      severe = c(sev_ids$G3, sev_ids$G4))
    
    ## calculation of the prediction stats
    
    pred_stats <- group_ids %>% 
      map(function(x) pred_results %>% 
            filter(ID %in% x) %>% 
            calculate_pred_stats)
    
    res_class <- pred_stats %>% 
      map(function(x) x$result_class)
    
    pred_stats <- pred_stats %>% 
      map2_dfr(., names(.), 
               function(x, y) mutate(x$stats, subset = y))
    
    ## ROC plot
    
    plotting_tbl <- res_class %>% 
      map2_dfr(., names(.), 
               function(x, y) mutate(x, subset = y)) %>% 
      mutate(pred_outcome = as.numeric(as.character(pred_outcome)))
    
    roc_plot <- plotting_tbl %>% 
      plot_roc(m_variable = 'pred_outcome', 
               d_variable = 'true_outcome', 
               marker_variable = 'subset', 
               labels = F) + 
      scale_color_manual(values = c(cohort = 'gray30', 
                                    mild = 'coral3', 
                                    severe = 'coral4'), 
                         labels = c(cohort = 'Cohort', 
                                    mild = 'Mild - moderate acute COVID', 
                                    severe = 'Severe - critical acute COVID'), 
                         name = '') + 
      geom_abline(slope = 1, 
                  intercept = 0, 
                  linetype = 'dashed') + 
      style_roc(guide = F) + 
      theme(plot.title = globals$common_text, 
            plot.margin = globals$common_margin, 
            axis.text = globals$common_text, 
            axis.title = globals$common_text)

    ## annotating the ROC plot with the accuracy values
    
    annot_tbl <- pred_stats %>% 
      mutate(acc_label = paste(signif(correct_rate * 100, 2), '%', sep = ''), 
             x = 0.75, 
             y = seq(0.4, 0.2, by = -0.1), 
             pred_outcome = 1, 
             true_outcome = 1)
    
    roc_plot <- roc_plot + 
      geom_text(data = annot_tbl, 
                aes(x = x, 
                    y = y, 
                    label = acc_label), 
                size = 2.75, 
                fontface = 'bold', 
                show.legend = F)
    
    return(list(result_class = res_class, 
                plot = roc_plot, 
                stats = pred_stats))
    
  }
  
# generating one-out vectors, analysis table -----
  
  insert_msg('Generating the analysis tables and test/train splits')

  cov_knn_verif$tbl_splits <- knn_size$analysis_tbls %>% 
    map(cov_knn_verif$make_splits)
  
# serial prediction by distance-weighted kNN and naive Bayes ------
  
  insert_msg('Serial prediction')
  
  ## kNN
  
  plan('multisession')
  
  cov_knn_verif$knn_predictions <- cov_knn_verif$tbl_splits %>% 
    future_map2(., names(.), 
                cov_knn_verif$test_accuracy,
                test_fun = knn, 
                k = 5, 
                kernel_fun = function(x) 1/x, 
                .options = furrr_options(seed = T))
  
  plan('sequential')
  
  ## naive Bayes
  
  cov_knn_verif$naive_bayes_predictions <- cov_knn_verif$tbl_splits %>% 
    map2(., names(.), 
         cov_knn_verif$test_accuracy,
         test_fun = naive_bayes)
  
# appending the results with the patient group assignment information -----
  
  insert_msg('Appending the modeling results with the severity group variable')
  
  cov_knn_verif$knn_predictions <- cov_knn_verif$knn_predictions %>% 
    map(left_join, 
        cov_data$long_data %>% 
          filter(time == 0) %>% 
          select(ID, pat_group), 
        by = 'ID')
  
  cov_knn_verif$naive_bayes_predictions <- cov_knn_verif$naive_bayes_predictions %>% 
    map(left_join, 
        cov_data$long_data %>% 
          filter(time == 0) %>% 
          select(ID, pat_group), 
        by = 'ID')
  
# calculating se, sp and accuracy of each algorithm in the entire cohort and severity groups ----
  
  insert_msg('Prediction quality in the whole cohort and severity groups')
  
  cov_knn_verif$knn_qc_stats <- cov_knn_verif$knn_predictions %>% 
    map(cov_knn_verif$calculate_stats)
  
  cov_knn_verif$naive_bayes_qc_stats <- cov_knn_verif$naive_bayes_predictions %>% 
    map(cov_knn_verif$calculate_stats)
  
# END -----
  
  insert_tail()